### ISSUE TITLE
Video getting stuck after the other user leaves the room

### ISSUE THREAD

**Issue by shrey1608** [WebDevSimplified/Zoom-Clone-With-WebRTC#14]
when the user leaves the room the video gets stuck and doesn't clear out after some time.

**Comment by micaiah-effiong** [comment]
You need to close the connection of the user that just left... 
- To do this you will have to listen to a socket disconnect event on the server, and run io.emit  with the corresponding peerId.
- On the front listen for disconnect, and run
`myPeer.connections[peerId][0].close()`

Hope this helps...
Waiting to get your feedback

**Comment by akkhilaysh** [comment]
Take a look at my recently opened Pull Request #25. It offers a solution to this issue.
