### ISSUE TITLE
connection over IP address is not secured 

### ISSUE THREAD

**Issue by tuminzee** [WebDevSimplified/Zoom-Clone-With-WebRTC#19]
connecting via ip address over the same network does not ask for user media permissions, because of which I am not able to connect it via mobile browser, or any other browser.

Local connection with localhost:3000 works just fine. 
But connection over IP address is not asking for UserMedia permissions

**Comment by micaiah-effiong** [comment]
To connect other devices, you will use the https module since userMedia is required to run on a secured http protocol

**Comment by tuminzee** [comment]
hi @micaiah-effiong 
I read about that, after that I deployed it on [Heroku](node-zoom-clone.herokuapp.com/),
though I was able to access the User Media (and all the permissions were asked)
I was unable to set up multiple video grid. Even though multiple connections would join the same room, no multiple screens would be created.
thank you replying
![Screenshot_2020-08-09 Zoom Clone1](https://user-images.githubusercontent.com/58180803/89729372-b2ca5780-da52-11ea-9d18-11db07c342e4.png)

**Comment by micaiah-effiong** [comment]
Is there any errors on your dev console?

**Comment by tuminzee** [comment]
Nope no error message

**Comment by micaiah-effiong** [comment]
Did your code run locally before you deployed it?
