### ISSUE TITLE
How to take this app online

### ISSUE THREAD

**Issue by BattleOfPlassey** [WebDevSimplified/Zoom-Clone-With-WebRTC#3]
How to deploy this app on Heroku or other cloud based deployement service.

**Comment by melvas6** [comment]
const myPeer = new Peer(undefined, {host:'peerjs-server.herokuapp.com', secure:true, port:443})

Changing to this works for Heroku as the default peer server is giving some issues.

**Comment by BattleOfPlassey** [comment]
> const myPeer = new Peer(undefined, {host:'peerjs-server.herokuapp.com', secure:true, port:443})
> 
> Changing to this works for Heroku as the default peer server is giving some issues.

After i replace this code i was able to launch the app but cannot see the video of the new joinee.

**Comment by BattleOfPlassey** [comment]
This happens in my localhost version as well :(

**Comment by melvas6** [comment]
For Heroku use for server port
server.listen(process.env.PORT || 5000)

For localhost did you try using -> Peer(undefined, {host:'peerjs-server.herokuapp.com', secure:true, port:443})

Works for me here https://webrtc121.herokuapp.com/ 
Although there are issues like sudden call drop. Any ideas?

**Comment by BattleOfPlassey** [comment]
Ofcourse i put process.env.PORT , also why would i put heroku URL in local host Peer() function if i am running locally, i tried cloning your code as well. i can only see one video at a time :D

**Comment by BattleOfPlassey** [comment]
![image](https://user-images.githubusercontent.com/35087196/88699181-a544d180-d124-11ea-91bb-39abe014c1cb.png)
Does this make sense?

**Comment by SilasK98** [comment]
How to access this app from other devices/outside? I already have trouble if I try to access it with the ip adress of my computer instead of localhost. It throws the error: Uncaught TypeError: Cannot read property 'getUserMedia' of undefined at script.js:11.
I guess thats due to the fact, that it is not running with https, but how to fix this?

**Comment by masterofyourmind** [comment]
> For Heroku use for server port
> server.listen(process.env.PORT || 5000)
> 
> For localhost did you try using -> Peer(undefined, {host:'peerjs-server.herokuapp.com', secure:true, port:443})
> 
> Works for me here https://webrtc121.herokuapp.com/
> Although there are issues like sudden call drop. Any ideas?

> Not able to receive the video of connected user

**Comment by ankitchouhan1020** [comment]
>  why would I put Heroku URL in localhost Peer() function if I am running locally.

Peer() function takes peer-js-server's host and port as arguments. He has deployed peer js sever on that URL.

**Comment by BattleOfPlassey** [comment]
> > why would I put Heroku URL in localhost Peer() function if I am running locally.
> 
> Peer() function takes peer-js-server's host and port as arguments. He has deployed peer js sever on that URL.

Thanks a ton Ankit and @melvas6 , It Works!! .
