### ISSUE TITLE
web to mobile video is not coming from phone 

### ISSUE THREAD

**Issue by avinashboy** [WebDevSimplified/Zoom-Clone-With-WebRTC#45]
https://user-images.githubusercontent.com/52669990/105630632-4ad8c380-5e70-11eb-82c3-9a3bd22ed813.mp4

Here is the link---->https://baby-kill.herokuapp.com/. Please let me know.

**Comment by okyanusoz** [comment]
Hello,
What browser is your phone using?

**Comment by avinashboy** [comment]
> Hello,
> What browser is your phone using?

Brave and chrome browser.
 but video is not sender to the web browser

**Comment by XxJrSxX** [comment]
Hello!!! Bro can you helpme please... how did you put the app on the web? cus i don't want yo work locally  ...... TY

**Comment by okyanusoz** [comment]
> > Hello,
> > What browser is your phone using?
> 
> Brave and chorme browser.
>  but video is not sender to the web browser

It is probably because the connection is not over HTTPS. Try using HTTPS in the server

**Comment by avinashboy** [comment]
> > > Hello,
> > > What browser is your phone using?
> > 
> > 
> > Brave and chorme browser.
> > but video is not sender to the web browser
> 
> It is probably because the connection is not över HTTPS. Try using HTTPS in the server

**Comment by avinashboy** [comment]
> > > Hello,
> > > What browser is your phone using?
> > 
> > 
> > Brave and chorme browser.
> > but video is not sender to the web browser
> 
> It is probably because the connection is not över HTTPS. Try using HTTPS in the server

Actually, I'm hosting in heroku. By default it's in HTTPS right..sorry I accidentally closed it.

**Comment by avinashboy** [comment]
> Hello!!! Bro can you helpme please... how did you put the app on the web? cus i don't want yo work locally ...... TY

use heroku it's free. here is link-->https://www.youtube.com/watch?v=MxfxiR8TVNU
