### ISSUE TITLE
Remote user video doesn't display

### ISSUE THREAD

**Issue by Emsyxen** [WebDevSimplified/Zoom-Clone-With-WebRTC#50]
Hello,

I tried to run the project but the remote video stream doesn't display. Only local video is displaying.  I saw on the youtube video that lots of people had the same issue. Any idea where it can come from?

It seems that the call doesn't get through and the myPeer.on('call') event lsitener is not firing.

**Comment by avinashboy** [comment]
> Hello,
> 
> I tried to run the project but the remote video stream doesn't display. Only local video is displaying. I saw on the youtube video that lots of people had the same issue. Any idea where it can come from?
> 
> It seems that the call doesn't get through and the myPeer.on('call') event listener is not firing.

https://github.com/WebDevSimplified/Zoom-Clone-With-WebRTC/issues/16

**Comment by avinashboy** [comment]
got it..
