### ISSUE TITLE
Node server crashes whenever I have more than one browser window open.

### ISSUE THREAD

**Issue by brendanreape88** [WebDevSimplified/Zoom-Clone-With-WebRTC#55]
I've followed the tutorial exactly and am able to see my video with one browser window open. However, for some reason my node server crashes when I open up another browser window with the same localhost address as the original browser to simulate multiple users being in one room together. 

Has anyone gotten these same errors and found a way to resolve them?

<img width="803" alt="Screen Shot 2021-03-11 at 8 12 06 PM" src="https://user-images.githubusercontent.com/59775185/110891283-8d325480-82a6-11eb-9af1-4cd973f09f3d.png">

<img width="367" alt="Screen Shot 2021-03-11 at 8 12 38 PM" src="https://user-images.githubusercontent.com/59775185/110891290-915e7200-82a6-11eb-8791-15aea208c0c1.png">

**Comment by keithlim** [comment]
replace `socket.to(roomId).broadcast.emit('user-connected', userId)` to `socket.broadcast.to(roomId).emit('user-connected', userId)`
